### ISSUE TITLE
Hemi, PnPn-2

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekExamples#67] opened 2017-05-11 16:46 UTC
The Hemi, PnPn-2 test case fails at link time with the following error:
``` console
mpif77 -o nek5000 obj/hemi.o obj/drive.o obj/drive1.o obj/drive2.o obj/plan4.o obj/bdry.o obj/coef.o obj/conduct.o obj/connect1.o obj/connect2.o obj/dssum.o obj/edgec.o obj/eigsolv.o obj/gauss.o obj/genxyz.o obj/navier1.o obj/makeq.o obj/navier0.o obj/navier2.o obj/navier3.o obj/navier4.o obj/prepost.o obj/speclib.o obj/map2.o obj/turb.o obj/mvmesh.o obj/ic.o obj/gfldr.o obj/ssolv.o obj/planx.o obj/math.o obj/mxm_wrapper.o obj/hmholtz.o obj/gfdm_par.o obj/gfdm_op.o obj/gfdm_solve.o obj/subs1.o obj/subs2.o obj/genbox.o obj/gmres.o obj/hsmg.o obj/convect.o obj/induct.o obj/perturb.o obj/navier5.o obj/navier6.o obj/navier7.o obj/navier8.o obj/fast3d.o obj/fasts.o obj/calcz.o obj/byte.o obj/chelpers.o obj/byte_mpi.o obj/postpro.o obj/intp_usr.o obj/cvode_driver.o obj/nek_comm.o obj/vprops.o obj/makeq_aux.o obj/papi.o obj/nek_in_situ.o obj/readat_new.o obj/reader_re2.o obj/finiparser.o obj/iniparser.o obj/dictionary.o obj/mxm_std.o obj/comm_mpi.o obj/singlmesh.o obj/blas.o obj/dsygv.o -L/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/3rd_party/gslib/src -lgs 
obj/hemi.o: In function `particle_out_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/NekExamples/hemi/hemi.f:469:(.text+0x14f): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/NekExamples/hemi/hemi.f:470:(.text+0x16d): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/NekExamples/hemi/hemi.f:475:(.text+0x227): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
obj/drive2.o: In function `dofcnt_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/drive2.f:1585:(.text+0x9314): relocation truncated to fit: R_X86_64_PC32 against symbol `scrns_' defined in COMMON section in obj/convect.o
obj/plan4.o: In function `crespsp_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/plan4.f:237:(.text+0xc65): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/plan4.f:252:(.text+0xd18): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/plan4.f:263:(.text+0xdab): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/plan4.f:246:(.text+0x10fb): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
obj/bdry.o: In function `trst3d_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/bdry.f:1662:(.text+0x387): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
obj/coef.o: In function `area3_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/coef.f:1221:(.text+0x3ce): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/coef.f:1221:(.text+0x3d5): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make: *** [nek5000] Error 1
```

**Comment by stgeke** [comment] 2017-05-11 16:49
Should be fixed in the latest version.

On 11 May 2017, at 18:45, Ron Rahaman <notifications@github.com <mailto:notifications@github.com> > wrote:

The Hemi, PnPn-2 test case fails at link time with the following error:


mpif77 -o nek5000 obj/hemi.o obj/drive.o obj/drive1.o obj/drive2.o obj/plan4.o obj/bdry.o obj/coef.o obj/conduct.o obj/connect1.o obj/connect2.o obj/dssum.o obj/edgec.o obj/eigsolv.o obj/gauss.o obj/genxyz.o obj/navier1.o obj/makeq.o obj/navier0.o obj/navier2.o obj/navier3.o obj/navier4.o obj/prepost.o obj/speclib.o obj/map2.o obj/turb.o obj/mvmesh.o obj/ic.o obj/gfldr.o obj/ssolv.o obj/planx.o obj/math.o obj/mxm_wrapper.o obj/hmholtz.o obj/gfdm_par.o obj/gfdm_op.o obj/gfdm_solve.o obj/subs1.o obj/subs2.o obj/genbox.o obj/gmres.o obj/hsmg.o obj/convect.o obj/induct.o obj/perturb.o obj/navier5.o obj/navier6.o obj/navier7.o obj/navier8.o obj/fast3d.o obj/fasts.o obj/calcz.o obj/byte.o obj/chelpers.o obj/byte_mpi.o obj/postpro.o obj/intp_usr.o obj/cvode_driver.o obj/nek_comm.o obj/vprops.o obj/makeq_aux.o obj/papi.o obj/nek_in_situ.o obj/readat_new.o obj/reader_re2.o obj/finiparser.o obj/iniparser.o obj/dictionary.o obj/mxm_std.o obj/comm_mpi.o obj/singlmesh.o obj/blas.o obj/dsygv.o -L/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/3rd_party/gslib/src -lgs 
obj/hemi.o: In function `particle_out_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/NekExamples/hemi/hemi.f:469:(.text+0x14f): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/NekExamples/hemi/hemi.f:470:(.text+0x16d): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/NekExamples/hemi/hemi.f:475:(.text+0x227): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
obj/drive2.o: In function `dofcnt_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/drive2.f:1585:(.text+0x9314): relocation truncated to fit: R_X86_64_PC32 against symbol `scrns_' defined in COMMON section in obj/convect.o
obj/plan4.o: In function `crespsp_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/plan4.f:237:(.text+0xc65): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/plan4.f:252:(.text+0xd18): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/plan4.f:263:(.text+0xdab): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/plan4.f:246:(.text+0x10fb): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
obj/bdry.o: In function `trst3d_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/bdry.f:1662:(.text+0x387): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
obj/coef.o: In function `area3_':
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/coef.f:1221:(.text+0x3ce): relocation truncated to fit: R_X86_64_32S against symbol `scrns_' defined in COMMON section in obj/convect.o
/sandbox/jenkins-ci/workspace/Nek5000/COMPILER/gnu/TEST_CASE/Hemi/Nek5000/core/coef.f:1221:(.text+0x3d5): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make: *** [nek5000] Error 1

**Comment by RonRahaman** [comment] 2017-05-11 16:54
Hmm, that's not what I see in Jenkins right now.

**Comment by stgeke** [comment] 2017-05-11 20:27
Fixed in the latest version. Now there is another problem:
FAILURE: wmax: Test value 0.48305 exceeds target value 0.47915 +/- 1e-06

**Comment by stgeke** [comment] 2017-05-18 08:22
@adampep Did you look into this?

**Comment by adampep** [comment] 2017-05-19 10:22
no. the whole week I was at parcfd

**Comment by stgeke** [comment] 2017-05-22 17:35
This https://github.com/Nek5000/Nek5000/commit/91413ddc7ac5eddf90c2c8561675758d4a734e31 improved the results. However it still fails:
FAILURE: wmax: Test value 0.47972 exceeds target value 0.47915 +/- 1e-06

The remaining difference is related to the changed plag initialization.
I recommend to change the target value to 0.47972.

**Comment by adampep** [comment] 2017-05-26 11:54
I've finally found it. Caused by commit 9bf13ae, that corrects pressure in the second step. Like in ext_cyl the new value should be better than the last one. As Stefan last time increased delta, I will do the same this time

**Comment by stgeke** [comment] 2017-06-02 11:53
Fixed https://github.com/Nek5000/NekExamples/commit/648bde072da8f7c3aed11acb58f931657196bce5

**Closed by stgeke** 2017-06-02 11:53 UTC
Labels: root cause identified
